### ISSUE TITLE
org.gradle.util.VersionNumber is being deprecated

### ISSUE THREAD

**Issue by enaess** [google/osdetector-gradle-plugin#34]
I am getting deprecated warnings for classes scheduled to be removed in Gradle 9.0

```
The org.gradle.util.VersionNumber type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#org_gradle_util_reports_deprecations
	at org.gradle.util.VersionNumber.logDeprecation(VersionNumber.java:37)
	at org.gradle.util.VersionNumber.compareTo(VersionNumber.java:112)
	at com.google.gradle.osdetector.OsDetector.compareGradleVersion(OsDetector.java:96)
	at com.google.gradle.osdetector.OsDetector.getImpl(OsDetector.java:85)
	at com.google.gradle.osdetector.OsDetector.getClassifier(OsDetector.java:63)
	at com.google.gradle.osdetector.OsDetector_Decorated.getClassifier(Unknown Source)
```

Also, there doesn't seem to be a recommended replacement for this API, maybe find a semver package or write one yourselves?

See
https://stackoverflow.com/questions/69967885/whats-the-successor-of-org-gradle-util-versionnumber

**Comment by ejona86** [comment]
Did you try upgrading? `VersionNumber` was removed from the plugin in 1.7.1.

**Comment by enaess** [comment]
I'll have another look with the latest version. And I am probably wrong here as I must have eye-balled the wrong import mistaking it for VersionNumber:

https://github.com/google/osdetector-gradle-plugin/blob/d152535dc886463fe6768fcc583fb730c171176f/src/main/java/com/google/gradle/osdetector/OsDetector.java#L31

**Comment by enaess** [comment]
Did the upgrade and the warning went away, closing the issue.
