### ISSUE TITLE
Revisit classifierWithLikes 

### ISSUE THREAD

**Issue by zhangkun83** [google/osdetector-gradle-plugin#4]
Setting `classifierWithLikes` changes the content of the classifier. Because there is only one classifier instance in on JVM, if different components want different `classifierWithLikes` settings, they will run into each other. A real world example is in gRPC Java build, both tcnative artifact and protobuf-gradle-plugin are using classifier, while tcnative sets `classifierWithLikes` and protobuf-gradle-plugin doesn't.

We should either allow multiple classifiers in a JVM (by making it non-static), or remove the `classifierWithLikes` feature.

@ejona86

**Comment by vans88** [comment]
I have built osdetector-gradle-plugin successfully. But when I run "./gradlew test" in top dir of this plugin and got the following error. Any suggestions on "setClassifierWithLikes FAILED".
**part of the error information:**
com.google.gradle.osdetector.OsDetectorPluginTest > **_### setClassifierWithLikes_** FAILED
    kr.motd.maven.os.DetectionException: unknown os.arch: mips64el
        at kr.motd.maven.os.Detector.detect(Detector.java:73)
        at com.google.gradle.osdetector.OsDetector$Impl.<init>(OsDetector.java:117)
        at com.google.gradle.osdetector.OsDetector.getImpl(OsDetector.java:64)
        at com.google.gradle.osdetector.OsDetector.getOs(OsDetector.java:34)
        at com.google.gradle.osdetector.OsDetector_Decorated.getOs(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:60)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
        at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
        at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
        at com.google.gradle.osdetector.OsDetector_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at com.google.gradle.osdetector.OsDetectorPluginTest.setClassifierWithLikes(OsDetectorPluginTest.groovy:53)

2 tests completed, 2 failed
Finished generating test XML results (0.278 secs) into: /usr/local/TenFlow/osdetector-gradle-plugin/build/test-results
Generating HTML test report...
Finished generating test html results (0.384 secs) into: /usr/local/TenFlow/osdetector-gradle-plugin/build/reports/tests
:test FAILED
:test (Thread[main,5,main]) completed. Took 26.676 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///usr/local/TenFlow/osdetector-gradle-plugin/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 20.901 secs
Stopped 0 compiler daemon(s).

**Comment by xzy256** [comment]
@zhangkun83 

> We should either allow multiple classifiers in a JVM (by making it non-static), or remove the  classifierWithLikes feature.

how to do? could you give more details for setting multiple classifiers in a JVM  or removing the  classifierWithLikes feature

**Comment by C3s1r3m** [comment]
César Dé Jesús Castellanos CDC alministrador y propietario de proyecto services Hash tags DOCS does doesn oh Criptomonedas Bitcoin Ethereum Dashboard http:// de followen digital software 2014 2015 2016 2017 2018 2019 20 2021 2022 All of on oír or in out oup it

**Comment by C3s1r3m** [comment]
content/admin/enterprise-management/updating-the-virtual-machine-and-physical-resources/enabling-automatic-update-checks.md

**Comment by Vampire** [comment]
The readme says since 9 years that this will be changed or removed "in the next version".
Maybe this should either be done, or at least the "next version" promise removed from the readme.

**Comment by tisonkun** [comment]
FWIW, I try to pick up this plugin and this crate according this background - https://github.com/trustin/os-maven-plugin/issues/70#issuecomment-1906110062

And now I create https://github.com/tisonspieces/os-detector/issues/7 and https://github.com/tisonspieces/os-detector/issues/6 to move the os detector lib forward, esp. the FFM JEP is ready to release and I can see a future that we need to handle different platform switchers in the Java code and build logic.
