### ISSUE TITLE
Faile build on PPC64LE system

### ISSUE THREAD

**Issue by apollos** [google/osdetector-gradle-plugin#7]
I try to build a UTXO java client on PPC64LE system, but I failed at the osdetector part as followed:

r
09:15:18.829 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Mutating platformResolver using ComponentModelBasePlugin.Rules#platformResolver
09:15:18.829 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'platformResolver' to state Discovered.
09:15:19.097 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.check' from state Registered to Initialized
09:15:19.097 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Running model element 'tasks.check' rule action tasks.addPlaceholderAction(check)
09:15:19.097 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Mutating tasks.check using tasks.addPlaceholderAction(check)
09:15:19.097 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.check' to state Discovered.
09:15:19.098 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Running model element 'tasks.check' rule action tasks.addPlaceholderAction(check)
09:15:19.098 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Mutating tasks.check using tasks.addPlaceholderAction(check)
09:15:19.098 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.check' to state Created.
09:15:19.099 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.check' to state DefaultsApplied.
09:15:19.099 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Running model element 'tasks.check' rule action copyToTaskContainer
09:15:19.099 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Mutating tasks.check using copyToTaskContainer
09:15:19.099 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.check' to state Initialized.
09:15:19.257 [INFO] [com.google.gradle.osdetector.OsDetector] ------------------------------------------------------------------------
09:15:19.258 [INFO] [com.google.gradle.osdetector.OsDetector] Detecting the operating system and CPU architecture
09:15:19.258 [INFO] [com.google.gradle.osdetector.OsDetector] ------------------------------------------------------------------------
09:15:19.258 [INFO] [com.google.gradle.osdetector.OsDetector] os.detected.name=linux
**09:15:19.259 [INFO] [com.google.gradle.osdetector.OsDetector] os.detected.arch=unknown**
09:15:19.259 [INFO] [com.google.gradle.osdetector.OsDetector] os.detected.classifier=linux-unknown
09:15:19.261 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 2.063 secs
09:15:19.294 [ERROR] [org.gradle.BuildExceptionReporter] 
09:15:19.294 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:15:19.294 [ERROR] [org.gradle.BuildExceptionReporter] 
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/gpfs_bk/sysongyu/workspace/yu/obc-utxo-client-java/build.gradle' line: 12
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] 
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'obc-utxo-client-java'.
09:15:19.295 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to apply plugin [id 'osdetector']
09:15:19.296 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not create an instance of type com.google.gradle.osdetector.OsDetectorExtension_Decorated.
09:15:19.296 [ERROR] [org.gradle.BuildExceptionReporter] 

Is there a work around for OsDector to work on PPC64LE system?

**Comment by zhangkun83** [comment]
For the exception, can you run your build with `--stacktrace` and post the stack trace here?

For detecting PPC64LE system, please file a bug to the [os-maven-plugin](https://github.com/trustin/os-maven-plugin) first. Once it's supported by os-maven-plugin, I can upgrade osdetector-gradle-plugin to use the new os-maven-plugin.

**Comment by SriramaSharma** [comment]
The support for ppc64le architecture has already been included into os-maven-plugin 1.3.0 (below references to commit) and also I see osdetector-gradle-plugin now makes use of maven 1.4.1. Still the issue of arch not being detected is seen. Am I missing anything here ?

Reference - https://github.com/trustin/os-maven-plugin/commit/dc58a0973fda90f448d073093bf08440a39ab4ca and https://github.com/trustin/os-maven-plugin/commit/47bde68c61e81fd0e703333fe6f527b837fc6647

**Comment by vans88** [comment]
Hello Every one, what about mips64el?  I need build grpc-java, which uses osdetector-gradle-plugin and os-maven-plugin,  when I run the following command, I get something error like the front. I have build os-maven-plugin-1.4.1.Final successfully.

My Errors info:
[root@dscn2 grpc-java]# ./gradlew  build --stacktrace --info
Starting Build
Settings evaluated using settings file '/usr/local/TenFlow/grpc-java/settings.gradle'.
Projects loaded. Root project using build file '/usr/local/TenFlow/grpc-java/build.gradle'.
Included projects: [root project 'grpc', project ':grpc-all', project ':grpc-auth', project ':grpc-benchmarks', project ':grpc-compiler', project ':grpc-context', project ':grpc-core', project ':grpc-grpclb', project ':grpc-interop-testing', project ':grpc-netty', project ':grpc-okhttp', project ':grpc-protobuf', project ':grpc-protobuf-lite', project ':grpc-protobuf-nano', project ':grpc-services', project ':grpc-stub', project ':grpc-testing', project ':grpc-thrift']
Evaluating root project 'grpc' using build file '/usr/local/TenFlow/grpc-java/build.gradle'.
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name=linux
os.detected.arch=unknown

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/TenFlow/grpc-java/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating root project 'grpc'.
> unknown os.arch: mips64el

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'grpc'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: kr.motd.maven.os.DetectionException: unknown os.arch: mips64el
        at kr.motd.maven.os.Detector.detect(Detector.java:73)
        at com.google.gradle.osdetector.OsDetector$Impl.<init>(OsDetector.java:117)
        at com.google.gradle.osdetector.OsDetector.getImpl(OsDetector.java:64)
        at com.google.gradle.osdetector.OsDetector.getOs(OsDetector.java:34)
        at com.google.gradle.osdetector.OsDetector_Decorated.getOs(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:196)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:149)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at com.google.gradle.osdetector.OsDetector_Decorated.getProperty(Unknown Source)
        at build_c2tft5gl5msegwe1eu549jhav$_run_closure1$_closure7.doCall(/usr/local/TenFlow/grpc-java/build.gradle:60)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_c2tft5gl5msegwe1eu549jhav$_run_closure1.doCall(/usr/local/TenFlow/grpc-java/build.gradle:59)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:888)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:893)
        at org.gradle.api.internal.project.AbstractProject.subprojects(AbstractProject.java:876)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:374)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_c2tft5gl5msegwe1eu549jhav.run(/usr/local/TenFlow/grpc-java/build.gradle:11)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 50 more


BUILD FAILED

Total time: 45.701 secs
Stopped 0 compiler daemon(s).

**Comment by zhangkun83** [comment]
What do you get if you add the following line to your `build.gradle`:
```
println "System os.arch=" + System.getProperty("os.arch")
```
and run `./gradlew projects`?

**Comment by vans88** [comment]
**@zhangkun83**   Many thanks for you reply.  I have done the following tests:

```
[root@dscn2 osdetector-gradle-plugin]# pwd
/usr/local/TenFlow/osdetector-gradle-plugin
[root@dscn2 osdetector-gradle-plugin]# ./gradlew projects
System os.arch=mips64el
:projects

------------------------------------------------------------
Root project - A Gradle plugin that detects the OS name and architecture, providing a uniform classifier to be used in the names of native artifacts.
------------------------------------------------------------

Root project 'osdetector-gradle-plugin' - A Gradle plugin that detects the OS name and architecture, providing a uniform classifier to be used in the names of native artifacts.
No sub-projects

To see a list of the tasks of a project, run gradlew <project-path>:tasks
For example, try running gradlew :tasks

BUILD SUCCESSFUL

Total time: 1 mins 3.25 secs
```

**Comment by vans88** [comment]
**@zhangkun83**  I do not know whether the above test results prove that the `osdetector-gradle-plugin`  has been installed correctly.There is a direct dependency between `grpc-java` and  `osdetector-gradle-plugin` .

## some information
```
[root@dscn2 grpc-java]# grep "osdetector-gradle-plugin" . -rn
./build.gradle:7:    classpath 'com.google.gradle:osdetector-gradle-plugin:1.4.1-SNAPSHOT'
./SECURITY.md:73:Gradle you can use the [osdetector-gradle-plugin](https://github.com/google/osdetector-gradle-plugin), which is a wrapper around the os-maven-plugin.
./SECURITY.md:163:Gradle you can use the [osdetector-gradle-plugin](https://github.com/google/osdetector-gradle-plugin), which is a wrapper around the os-maven-plugin.
./SECURITY.md:171:    classpath 'com.google.gradle:osdetector-gradle-plugin:1.4.0'
./SECURITY.md:175:// Use the osdetector-gradle-plugin
./compiler/check-artifact.sh:8:# osdetector-gradle-plugin
```

**Comment by vans88** [comment]
## Build `grpc-java`
Base on the above, I run the command " ./gradlew build --debug" to build. But I still get the following error and abort the compilation

```
10:56:09.047 [QUIET] [system.out] System os.arch=mips64el
10:56:09.110 [INFO] [com.google.gradle.osdetector.OsDetector] ------------------------------------------------------------------------
10:56:09.112 [INFO] [com.google.gradle.osdetector.OsDetector] Detecting the operating system and CPU architecture
10:56:09.114 [INFO] [com.google.gradle.osdetector.OsDetector] ------------------------------------------------------------------------
10:56:09.121 [INFO] [com.google.gradle.osdetector.OsDetector] os.detected.name=linux
10:56:09.123 [INFO] [com.google.gradle.osdetector.OsDetector] os.detected.arch=unknown
10:56:09.130 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 25.275 secs
10:56:09.219 [ERROR] [org.gradle.BuildExceptionReporter]
10:56:09.222 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:56:09.224 [ERROR] [org.gradle.BuildExceptionReporter]
10:56:09.226 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
10:56:09.227 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/usr/local/TenFlow/grpc-java/build.gradle' line: 61
10:56:09.229 [ERROR] [org.gradle.BuildExceptionReporter]
10:56:09.231 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:56:09.233 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'grpc'.
10:56:09.235 [ERROR] [org.gradle.BuildExceptionReporter] > unknown os.arch: mips64el
10:56:09.237 [ERROR] [org.gradle.BuildExceptionReporter]
10:56:09.238 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
10:56:09.240 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
10:56:09.246 [LIFECYCLE] [org.gradle.BuildResultLogger]
10:56:09.249 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
10:56:09.251 [LIFECYCLE] [org.gradle.BuildResultLogger]
10:56:09.253 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 47.931 secs
```

## code segment from build.gradle in grpc-java top dir
```
     59     ext {
     60         println "System os.arch=" + System.getProperty("os.arch")
     61         def exeSuffix = osdetector.os == 'windows' ? ".exe" : ""
     62         protocPluginBaseName = 'protoc-gen-grpc-java'
     63         javaPluginPath = "$rootDir/compiler/build/exe/java_plugin/$protocPluginBaseName$exeSuffix"
     64
     65         guavaVersion = '19.0'
     66         protobufVersion = '3.0.2'
     67         protobufNanoVersion = '3.0.0-alpha-5'


```

**Comment by vans88** [comment]
**@zhangkun83**  Could you give me some suggestions to fix the errors?  if the errors have nothing to do with `osdetector-gradle-plugin` and `os-maven-plugin`, should I close the comment and create a new issue aboute `grpc-java`?

**Comment by ejona86** [comment]
Looks like ppc detection has been working for a while. And the grpc-java thing would have been appropriate for grpc-java repository, not here, but grpc-java also has had a ppc64le build for years now.
